version: '3.8'

services:
  # Laravel Application
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - laravel_network
    depends_on:
      - mongodb

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Using 8080 to avoid conflict with Herd
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: laravel_mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"  # Using 27018 to avoid conflict with local MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: laravel
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: laravel_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - laravel_network

  # Redis (for caching/sessions)
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # Using 6380 to avoid conflict with local Redis
    networks:
      - laravel_network

volumes:
  mongodb_data:

networks:
  laravel_network:
    driver: bridge